#!/bin/sh

clang_dir=$1
target=include/env/impl.hpp

# Create directories if they don't exist
mkdir -p include/env/

# Remove the impl.hpp to create a fresh one, since the PWD changes.
[ -f $target ] && rm -f $target
cat <<EOF > $target
/* XXX: Automagically generated. No touching. */
#pragma once

namespace color_coded
{
  template <>
  struct environment<env::tag>
  {
    static char constexpr const * const pwd{ "$PWD" };
    static char constexpr const * const clang_include
    { "-isystem$clang_dir/include" };
    static char constexpr const * const clang_include_cpp
    { "-isystem$clang_dir/include/c++/v1" };
    static char constexpr const * const clang_lib_include
    { "-isystem$clang_dir/lib/clang/3.8.0/include" };
  };
}
EOF
