message(STATUS "Looking for Lua >= 5.1")
find_package(Lua QUIET)
if((NOT ${LUA_FOUND}) OR (NOT DEFINED LUA_INCLUDE_DIR) OR (${LUA_INCLUDE_DIR} MATCHES "LUA_INCLUDE_DIR-NOTFOUND"))
    message(FATAL_ERROR "Lua was not found but is required")
endif()
if(${LUA_VERSION_STRING} VERSION_LESS "5.1")
    message(FATAL_ERROR "Lua version 5.1 or higher is required")
endif()
message(STATUS "Found Lua")
message(STATUS "  Lua include ${LUA_INCLUDE_DIR}")
message(STATUS "  Lua lib ${LUA_LIBRARIES}")

include_directories(${LUA_INCLUDE_DIR})
